// Fallback image URLs for products while Airtable images are being configured
export const productImages: Record<string, string> = {
  'heirloom-tomatoes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Heirloom_tomatoes.jpg/960px-Heirloom_tomatoes.jpg',
  'rainbow-carrots': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Carrots_of_many_colors.jpg/960px-Carrots_of_many_colors.jpg',
  'baby-spinach': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Spinach_leaves.jpg/960px-Spinach_leaves.jpg',
  'avocados': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/960px-Avocado_Hass_-_single_and_halved.jpg',
  'kale-bunch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Lacinato_kale.jpg/960px-Lacinato_kale.jpg',
  'strawberries': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Strawberries.jpg/960px-Strawberries.jpg',
  'meyer-lemons': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Meyer_Lemon.jpg/960px-Meyer_Lemon.jpg',
  'sourdough-loaf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Home_made_sour_dough_bread.jpg/960px-Home_made_sour_dough_bread.jpg',
  'baguette': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Baguettes%2C_Paris%2C_France_-_panoramio.jpg/960px-Baguettes%2C_Paris%2C_France_-_panoramio.jpg',
  'focaccia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Focaccia_with_Crumb.jpg/960px-Focaccia_with_Crumb.jpg',
  'croissants': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/960px-Croissant-Petr_Kratochvil.jpg',
  'rye-loaf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Market_Bread%2C_Riga%2C_Latvia.jpg/960px-Market_Bread%2C_Riga%2C_Latvia.jpg',
  'cinnamon-buns': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cinnamon_roll_in_Stockholm.jpg/960px-Cinnamon_roll_in_Stockholm.jpg',
  'king-salmon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Raw_salmon_fillets.jpg/960px-Raw_salmon_fillets.jpg',
  'bay-scallops': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Scallops.jpg/960px-Scallops.jpg',
  'halibut': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Hippoglossus_hippoglossus.jpg/960px-Hippoglossus_hippoglossus.jpg',
  'smoked-trout': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Smoked_trout.jpg/960px-Smoked_trout.jpg',
  'whole-milk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/960px-Glass_of_Milk_%2833657535532%29.jpg',
  'cultured-butter': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Homemade_butter.jpg/960px-Homemade_butter.jpg',
  'aged-cheddar': 'https://upload.wikimedia.org/wikipedia/commons/1/18/Somerset-Cheddar.jpg',
  'fresh-eggs': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/2020-05-05_19_27_12_An_open_carton_of_a_dozen_Large_Grade_A_Chicken_Eggs_from_Egg-land%27s_Best_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg/960px-thumbnail.jpg',
  'greek-yogurt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/960px-Joghurt.jpg',
  'mozzarella': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mozzarella_di_bufala3.jpg/960px-Mozzarella_di_bufala3.jpg',
  'olive-oil': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olive_oil_bottle_Bertolli_Riserva_Premium.jpg/960px-Olive_oil_bottle_Bertolli_Riserva_Premium.jpg',
  'tomato-sauce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Fresh_Tomato_Sauce_%28Unsplash%29.jpg/960px-Fresh_Tomato_Sauce_%28Unsplash%29.jpg',
  'pasta-bronze': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Rigatoni.jpg/960px-Rigatoni.jpg',
  'flaky-salt': 'https://upload.wikimedia.org/wikipedia/commons/8/8a/FleurDeSel.JPG',
  'honey-jar': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Runny_hunny.jpg/960px-Runny_hunny.jpg',
  'aged-balsamic': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Traditional_Balsamic_Vinegars_of_Modena_%28right%29_and_Reggio_Emilia_%28left%29.jpg/960px-Traditional_Balsamic_Vinegars_of_Modena_%28right%29_and_Reggio_Emilia_%28left%29.jpg',
  'kombucha': 'https://upload.wikimedia.org/wikipedia/commons/4/48/Kombucha_Mature.jpg',
  'sparkling-water': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Sparkling_Water_with_Mint_in_Glass_Cup.jpg/960px-Sparkling_Water_with_Mint_in_Glass_Cup.jpg',
  'cold-brew': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Iced_Coffee_in_Glass_-_Sunshine_Coffee_-_Laramie_Cafe_%2853838344552%29.jpg/960px-Iced_Coffee_in_Glass_-_Sunshine_Coffee_-_Laramie_Cafe_%2853838344552%29.jpg',
  'dark-chocolate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Green_and_Black%27s_dark_chocolate_bar_2.jpg/960px-Green_and_Black%27s_dark_chocolate_bar_2.jpg',
  'roasted-almonds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Heap_of_almonds.jpg/960px-Heap_of_almonds.jpg',
  'sea-salt-chips': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Potato_Chips.jpg/960px-Potato_Chips.jpg',
  'granola': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Granola_with_soymilk_and_berries_flickr_user_rubbermaid_products.jpg/960px-Granola_with_soymilk_and_berries_flickr_user_rubbermaid_products.jpg',
  'dark-chocolate-sea-salt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/2020-02-23_02_24_15_A_Ghirardelli_Dark_Chocolate_Mint_Square_broken_into_two_pieces_in_the_Parkway_Village_section_of_Ewing_Township%2C_Mercer_County%2C_New_Jersey.jpg/960px-thumbnail.jpg',
  'frozen-blueberries': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Blueberries.jpg',
  'garden-peas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Peas.jpg/960px-Peas.jpg',
  'vanilla-ice-cream': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Vanilla_ice_cream.jpg/960px-Vanilla_ice_cream.jpg',
  'margherita-pizza': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Frozen_pizza.jpg/960px-Frozen_pizza.jpg',
  'pork-dumplings': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Jiaozi.jpg/960px-Jiaozi.jpg',
  'sweet-potato-fries': 'https://upload.wikimedia.org/wikipedia/commons/8/83/French_Fries.JPG',
};

export function getImageUrl(slug: string, fallbackUrl?: string): string | undefined {
  return productImages[slug] || fallbackUrl;
}
